### ISSUE TITLE
Excessive use of `internal` and lack of `virtual` making modification near-impossible

### ISSUE THREAD

**Issue by trigger-segfault** [roslynpad/roslynpad#193]
RoslynPad is great for what it does, but due to the use of the `internal` keyword for almost every class in the library, overriding or customizing anything becomes quite difficult. Basically users are at the mercy of the developer to make exactly what they need changed or fixed an option or feature. There is no ability to fix it yourself. `virtual` methods is another instance that doesn't nearly have enough use. I will agree that the existing overridable methods are very helpful already but there are many more that could be implemented.

Of course if I could, I would just use the source for the library and modify that. But due to being constrained to VS 2015, it becomes impossible to build the library even if you remove all uses of C#7. Others may also not be lucky enough to be using VS 2017.

This is only a minor gripe as at the moment as I've pretty much got the editor to the point I want it to be at, but that was mostly through modifying AvalonEdit's source and referencing the project instead of the Nuget package. The other instance would be completely disabling brace completion through reflection, not just due to #121 , but also due to the coding style used for the brace completion forcing the opening brace to be on a new line.

**Comment by aelij** [comment]
Can you give concrete examples of internal types/virtual members you needed? Remember that I'm just one guy doing this on his free time… :) and I didn't design RP to be reusable from the get-go. The NuGet packages are relatively new.

Regarding C# 7 (or 7.2 to be precise), I'm afraid that's not going to change. You could compile in the command line. Or alternatively just download the VS community edition and use it just for RP. I think there's also an option to consume the compiler using [NuGet](https://www.nuget.org/packages/Microsoft.Net.Compilers/) but I've never tried it.

Another option is the build trick I use to access Roslyn's internals: https://github.com/aelij/IgnoresAccessChecksToGenerator

**Comment by trigger-death** [comment]
Sure, here are a few examples that I've encountered specifically.

* `RoslynCodeEditorCompletionProvider.Warmup()` is internal which is a minor setback when trying to create your own `RoslynCodeEditor` from `CodeEditor`.
* A lot (or maybe even all) extension methods seem to be internal which makes copying source code to make custom classes a lot more difficult.
* Basically everything in the `AutoCompletion` and `BraceMatching` namespace is internal which entirely prevented making a new brace completion method.

I should also note that some things seemed to be missing from outside RoslynPad like some Microsoft.CodeAnyalysis classes like `IFormattingRule` and the `Formatting.Rules` namespace in general. Not sure if they are only available in newer framework/standard versions or something else. But there's nothing that can be done about this so it's no big deal, just a little strange.

And sorry if I came off as nitpicky, I really do appreciate this library and you're a pretty awesome dev to be this on the ball for every issue in the GitHub repo, personal question or otherwise.

As for for the Nuget packages being new, well that explains things a bit so this issue certainly isn't something that would have been important before that.

Also that IgnoresAccessChecksToGenerator sounds really helpful again. Will definitely check that out for many different situations.
