### ISSUE TITLE
Tab character interpreted as space

### ISSUE THREAD

**Issue by pereverti** [roslynpad/roslynpad#455]
Tabs into a string are interpreted as spaces:

Sample code with tabs:

```
string input = @"    
Load ID]}           WESUN 
"; // this is your input string
string output = new string(input.Where(c => !char.IsControl(c)).ToArray()).Trim();

Console.WriteLine(input);
Console.WriteLine("-----------------------------------------------------");
Console.WriteLine(output);
```

![2023-01-24 15_08_35-RoslynPad 17](https://user-images.githubusercontent.com/5957255/214316454-748baa19-5dab-4927-847b-cd379b67d213.png)

The expected result is:

![2023-01-24 15_10_42-LINQPad 7](https://user-images.githubusercontent.com/5957255/214316797-20ed22dd-f157-4f1b-b606-4feba585c0d7.png)

**Comment by aelij** [comment]
Note the sample code doesn't actually contain tab chars. The problem is that the AvalonEdit editor is configured to convert tabs into spaces. I don't know if it's possible to configure the editor allow tabs only inside of a string.

You could:
* Configure the editor to use tabs for indentation using .editorconfig (`indent_style = tab`)
* Use an interpolated string to specify the tab char:
  ```cs
  string input = $@"    
    Load ID]}}{'\t'}WESUN 
  "; 
   ```
